### ISSUE TITLE
Please remove "our other projects section" from the site

### ISSUE THREAD

**Issue by shemeerp** [SocialGeeksIndia/AutismSupport#1]
<img width="454" alt="screenshot at aug 07 16-42-07" src="https://cloud.githubusercontent.com/assets/1499509/9134600/552644d0-3d23-11e5-91b1-cc8e06ffdb99.png">

**Comment by shivanayakd** [comment]
Removed the Our other projects section sir.

**Comment by shemeerp** [comment]
This is not closed. i can still see the our projects in the footer.

**Comment by shivanayakd** [comment]
Now it's removed sir, Please check, Thanks.
