### ISSUE TITLE
Contact Email to Freshdesk Support

### ISSUE THREAD

**Issue by shemeerp** [SocialGeeksIndia/AutismSupport#3]
Any submission from the contact form (http://autismsupport.in/contact-us-autism-support-helplines-india/) should become a fresh desk ticket. See here for details https://support.freshdesk.com/support/solutions/articles/37541-converting-your-support-email-into-freshdesk-tickets

**Comment by shivanayakd** [comment]
Hi sir, Now the submissions from the contact form of autismsupport.in is creating a ticket in the freshdesk , please send a test mail from contact us page of autismsupport.in , you can see the same ticket created in freshdesk.
